theme: jekyll-theme-minimal
title: Sunrise Movement Denver Hub\'s 2026 Midterm Elections Ballot Guide
description: Sunrise Movement volunteers in the Denver area asked candidates to answer a series of questions, which have been summarized here to give voter\'s a fast and simple way to be informed.
google_sheet_csv_url: "https://docs.google.com/spreadsheets/d/1O280SuRh7G5kVjNnzH8wXVgiDMzq2opBLzz9s3a2--Q/edit?resourcekey=&gid=1871626880#gid=1871626880"
